name: Snyk Docker Analysis

on:
  workflow_dispatch:

jobs:
  snyk-docker-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Install Snyk
        run: npm install -g snyk

      - name: Authenticate Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk auth $SNYK_TOKEN

      - name: Analyze Docker Image
        run: snyk container test your-account-id.dkr.ecr.us-east-1.amazonaws.com/your-repository-name:latest
