name: Docker Image Scan

on:
  workflow_dispatch:

jobs:
  docker-image-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: List Docker Images
        run: aws ecr list-images --repository-name mi-app-web --region us-east-1

      - name: Pull Docker Image
        run: |
          docker pull 202533506302.dkr.ecr.us-east-1.amazonaws.com/mi-app-web:latest

      - name: Install Snyk
        run: npm install -g snyk

      - name: Authenticate Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk auth $SNYK_TOKEN

      - name: Scan Docker Image
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          snyk container test 202533506302.dkr.ecr.us-east-1.amazonaws.com/mi-app-web:latest \
          --severity-threshold=high
